# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'default'

variables:
  buildConfiguration: 'Release'

steps:
- script: docker pull $(imageTag):latest  # add options to this command to meet your needs
  displayName: 'docker build id $(dockerId) and name $(imageName)'
 
